#include "nsISupports.idl"
#include "nsIDOMMediaStream.idl"
#include "nsIDOMCanvasRenderingContext2D.idl"
#include "nsrootidl.idl"
#include "nsIPropertyBag2.idl"

[scriptable, function, uuid(03E963EC-423E-474A-B346-00CAC8E6D124)]
interface INrtcObserver : nsISupports
{
    void onStateChanged(in string state, in string args);
};

[scriptable, uuid(86AD66E9-B3F7-4E6A-BEEE-802B1D9FF442)]
interface INrtc : nsISupports
{
  void startConference(in nsIPropertyBag2 prop, in INrtcObserver observer);
  void joinConference(in string conferencePrefix, in INrtcObserver observer);
  void leaveConference(in string conferencePrefix, in INrtcObserver observer);  
};
